src/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipName>Feedbacks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_Link__c</fullName>
        <label>Feedback Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Feedback_Validity_Date__c</fullName>
        <label>Feedback Validity Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rating_Group__c</fullName>
        <label>Rating Group</label>
        <referenceTo>Rating_Group__c</referenceTo>
        <relationshipLabel>Feedback Templates</relationshipLabel>
        <relationshipName>Feedback_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Email__c</fullName>
        <label>Staff Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Staff_Name__c</fullName>
        <label>Staff Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Feedback Templates</relationshipLabel>
        <relationshipName>Feedback_Templates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Feedback Template</label>
    <nameField>
        <displayFormat>Feedback-{00000}</displayFormat>
        <label>Feeback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_Data__c.object
<CustomObject>
    <fields>
        <fullName>Feedback_Name__c</fullName>
        <label>Feedback Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Name__c</fullName>
        <label>Question Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Roll_Number__c</fullName>
        <label>Student Roll Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Feedback Data</label>
    <nameField>
        <displayFormat>FBData-{000000}</displayFormat>
        <label>Feedback Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_Group__c.object
<CustomObject>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipLabel>Feedback Groups</relationshipLabel>
        <relationshipName>Feedback_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Feedback Groups</relationshipLabel>
        <relationshipName>Feedback_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Feedback Group</label>
    <nameField>
        <displayFormat>FG-{00000}</displayFormat>
        <label>Feedback Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grouped_Question__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Grouped Questions</relationshipLabel>
        <relationshipName>Grouped_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Grouped Questions</relationshipLabel>
        <relationshipName>Grouped_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grouped Question</label>
    <nameField>
        <displayFormat>GQ-{00000}</displayFormat>
        <label>Grouped Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grouped Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rating__c.object
<CustomObject>
    <label>Rating</label>
    <nameField>
        <label>Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rating_Group__c.object
<CustomObject>
    <label>Rating Group</label>
    <nameField>
        <label>Rating Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rating Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Rating_Group__c.object
<CustomObject>
    <fields>
        <fullName>Rating_Group__c</fullName>
        <label>Rating Group</label>
        <referenceTo>Rating_Group__c</referenceTo>
        <relationshipLabel>Related Rating Groups</relationshipLabel>
        <relationshipName>Related_Rating_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <referenceTo>Rating__c</referenceTo>
        <relationshipLabel>Related Rating Groups</relationshipLabel>
        <relationshipName>Related_Rating_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Related Rating Group</label>
    <nameField>
        <displayFormat>RG-{0000}</displayFormat>
        <label>Related Rating Groups Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Rating Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Email__c</fullName>
        <label>Staff Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Staff</label>
    <nameField>
        <displayFormat>Staff-{0000}</displayFormat>
        <label>Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeedbackQuestionController.cls
public class FeedbackQuestionController
{        
    String Id = System.currentPageReference().getParameters().get('id'); //
    public Feedback__c feedback {get; set;}    
    public String StudentRollNo { get; set;}
    public String[] rating = new String[]{};
    List<Grouped_Question__c> Question;
    public List<SelectOption> options = new List<SelectOption>();

    String forceURL = URL.getSalesforceBaseUrl().toExternalForm();

    public String[] getRating()
    {
        system.debug('getRating');
        return rating;
    }

    public void setRating(String[] rate)
    {
        system.debug('setRating array');
        rating = rate;
    }

    
    public void setRating(String rate)
    {
        system.debug('setRating single');
        rating.add(rate);
    }

    public FeedbackQuestionController(ApexPages.StandardController stdController)
    {
        system.debug('a');
        StudentRollNo = null;        
        feedback = [ SELECT name, Department__r.name, CreatedDate, Feedback_Link__c, Feedback_Validity_Date__c, Staff__c, Staff_Email__c, Staff_Name__c, Rating_Group__c FROM Feedback__c WHERE Id = :Id ];
        system.debug(feedback);        
    }

    public List<Grouped_Question__c> getQuestion()
    {
        system.debug('c');
        Question = [ SELECT Question__r.name, Group__r.name, Question__r.rating__c FROM Grouped_Question__c where Group__c in (SELECT Group__c FROM Feedback_Group__c WHERE Feedback__c = :Id ) ORDER BY Group__r.name, Question__r.name ];
        system.debug('Question : ' + Question);        
        return Question ;
    }

    public List<SelectOption> getItems()
    {
        system.debug('form rating');
        for ( Related_Rating_Group__c rating : [ SELECT Rating__r.name FROM Related_Rating_Group__c where rating_group__c = :feedback.Rating_Group__c ORDER BY Rating__r.name ] )
        {
            options.add(new SelectOption(rating.Rating__r.name, rating.Rating__r.name));
        
        }    
        system.debug('options :' + options);
        return options;
    }

    public PageReference validate()
    {
        system.debug('validate');

        if (feedback.Feedback_Validity_Date__c < system.now())
        {
            PageReference pageRef = new PageReference(forceURL+'/FeedbackValidatePage?id='+Id);
            return pageRef;
        }
        return null;        
    }

    public PageReference submitfeedback()
    {
        system.debug('submitfeedback');
       
        if ( [ SELECT count() FROM Feedback_Data__c where student_roll_number__c = :StudentRollNo and feedback_name__c = :feedback.name ] == 0 )
        {
            system.debug('Roll no and feedback not exists');
        
            List<Feedback_Data__c> feedbackdata = new List<Feedback_Data__c> ();
            Integer cnt = 0;
            
            system.debug('Question : ' + Question);
            for ( Grouped_Question__c grQ : Question )
            {
                feedbackdata.add( new Feedback_Data__c(feedback_name__c = feedback.name, Student_Roll_Number__c = StudentRollNo, Group_Name__c = grQ.group__r.name, Question_Name__c = grQ.question__r.name, Rating__c = rating[cnt] ));
                cnt++;
            }
            system.debug(feedbackdata);            
            insert feedbackdata;
        }
        PageReference pageRef = new PageReference(forceURL+'/FeedbackThankyouPage?id='+Id);
        return pageRef;
    }
    
    public PageReference sendLink()
    {
        system.debug('Inside sendLink ' + feedback.Staff_Email__c);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSenderDisplayName('clouddev@surashriconsultants.com');
        mail.setToAddresses(new String[] { feedback.Staff_Email__c });
        mail.setSubject('Your Feedback Link Attached');
        mail.setPlainTextBody('Please forward this link to your students for getting Feedback\nhttp://' + feedback.Feedback_Link__c);
        List <Messaging.SendEmailResult> results = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ mail });
        system.debug('Result ' + results);       
        return null;    
    }  
    
}