src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grouped_Question__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Grouped Questions</relationshipLabel>
        <relationshipName>Grouped_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Grouped Questions</relationshipLabel>
        <relationshipName>Grouped_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grouped Question</label>
    <nameField>
        <displayFormat>GQ-{00000}</displayFormat>
        <label>Grouped Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grouped Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateGroupName.cls
@isTest (SeeAllData=true)
private class TestUpdateGroupName 
{
    static testmethod void InsertGroupedQuestion()
	{
        Grouped_Question__c TestGrQ = new Grouped_Question__c(Group__c='a0A900000082NjF', Question__c='a03900000036j9V');
        Test.startTest();
		Database.SaveResult Sresult = Database.insert(TestGrQ, true);
		Test.stopTest();
        System.assert(Sresult.isSuccess());
	}

    static testmethod void DeleteGroupedQuestion()
	{
        Grouped_Question__c TestGrQ = new Grouped_Question__c(Group__c='a0A900000082NjF', Question__c='a03900000036j9V');
        Test.startTest();
		Database.SaveResult Sresult = Database.insert(TestGrQ, true);
        Database.DeleteResult Dresult = Database.delete(TestGrQ, true);
		Test.stopTest();
        System.assert(Dresult.isSuccess());
	}

}